'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
type Wallet={id:string;currency:string;balanceMinor:string;createdAt:string};type Transfer={id:string;fromWalletId:string;toWalletId:string;amountMinor:string;currency:string;status:string;createdAt:string};type User={id:string;name:string;email:string};type Endpoint={id:string;url:string;active:boolean;createdAt:string};type Delivery={id:string;attempt:number;statusCode:number;success:boolean;createdAt:string;event:{id:string;type:string;aggregateId:string};endpoint:{id:string;url:string}};type View='overview'|'webhooks'|'system';
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:4000/api';const money=(v:string|number,c='BRL')=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:c}).format(Number(v)/100);const idem=(p:string)=>`${p}-${crypto.randomUUID()}`;
export default function Home(){
 const[token,setToken]=useState('');const[user,setUser]=useState<User|null>(null);const[wallets,setWallets]=useState<Wallet[]>([]);const[transfers,setTransfers]=useState<Transfer[]>([]);const[mode,setMode]=useState<'login'|'register'>('login');const[view,setView]=useState<View>('overview');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[endpoints,setEndpoints]=useState<Endpoint[]>([]);const[deliveries,setDeliveries]=useState<Delivery[]>([]);const[newSecret,setNewSecret]=useState('');const[health,setHealth]=useState<any>(null);const wallet=wallets[0];
 const call=async(path:string,init:RequestInit={},activeToken=token)=>{const r=await fetch(`${API}${path}`,{...init,headers:{'content-type':'application/json',...(activeToken?{authorization:`Bearer ${activeToken}`}:{}),...init.headers}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(Array.isArray(d.message)?d.message.join(', '):d.message??'Request failed');return d};
 const refresh=async(t=token)=>{if(!t)return;const[me,w,tr]=await Promise.all([call('/auth/me',{},t),call('/wallets',{},t),call('/transfers',{},t)]);setUser(me);setWallets(w);setTransfers(tr)};
 const loadWebhooks=async()=>{const[e,d]=await Promise.all([call('/webhooks'),call('/webhooks/deliveries')]);setEndpoints(e);setDeliveries(d)};
 const loadSystem=async()=>{try{setHealth(await call('/health/ready'))}catch(e){setHealth({status:'not_ready',error:e instanceof Error?e.message:'Unavailable'})}};
 useEffect(()=>{const t=localStorage.getItem('ledgerx_token');if(t){setToken(t);void refresh(t).catch(()=>localStorage.removeItem('ledgerx_token'))}},[]);
 useEffect(()=>{if(token&&view==='webhooks')void loadWebhooks();if(token&&view==='system')void loadSystem()},[view,token]);
 const auth=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget);try{const payload=mode==='register'?{name:f.get('name'),email:f.get('email'),password:f.get('password')}:{email:f.get('email'),password:f.get('password')};const d=await call(`/auth/${mode}`,{method:'POST',body:JSON.stringify(payload)},'');localStorage.setItem('ledgerx_token',d.accessToken);setToken(d.accessToken);await refresh(d.accessToken)}catch(e){setMessage(e instanceof Error?e.message:'Authentication failed')}finally{setBusy(false)}};
 const fund=async()=>{if(!wallet)return;setBusy(true);try{await call(`/wallets/${wallet.id}/fund`,{method:'POST',headers:{'Idempotency-Key':idem('fund')},body:JSON.stringify({amountMinor:10000})});await refresh();setMessage('R$ 100,00 added to the simulated wallet.')}catch(e){setMessage(e instanceof Error?e.message:'Funding failed')}finally{setBusy(false)}};
 const transfer=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!wallet)return;const form=e.currentTarget;setBusy(true);const f=new FormData(form);try{await call('/transfers',{method:'POST',headers:{'Idempotency-Key':idem('transfer')},body:JSON.stringify({fromWalletId:wallet.id,toWalletId:f.get('walletId'),amountMinor:Number(f.get('amount'))})});await refresh();e.currentTarget.reset();setMessage('Transfer posted atomically.')}catch(x){setMessage(x instanceof Error?x.message:'Transfer failed')}finally{setBusy(false)}};
 const createWebhook=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setNewSecret('');const f=new FormData(form);try{const d=await call('/webhooks',{method:'POST',body:JSON.stringify({url:f.get('url')})});setNewSecret(d.secret);form.reset();await loadWebhooks()}catch(x){setMessage(x instanceof Error?x.message:'Webhook creation failed')}finally{setBusy(false)}};
 const balance=useMemo(()=>money(wallet?.balanceMinor??0,wallet?.currency),[wallet]);
 if(!token||!user)return <main className="auth-shell"><section className="hero"><div className="brand">LX</div><p className="eyebrow">FINANCIAL SYSTEMS ENGINEERING</p><h1>Money movement,<br/><span>engineered correctly.</span></h1><p className="lead">A production-minded payment simulation with double-entry accounting, idempotency, serializable transactions, outbox events and signed webhooks.</p><div className="chips"><span>PostgreSQL</span><span>Redis + BullMQ</span><span>Double-entry ledger</span></div></section><section className="auth-card"><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Sign in</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Create account</button></div><form onSubmit={auth}>{mode==='register'&&<label>Name<input name="name" required minLength={2}/></label>}<label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required minLength={8}/></label>{message&&<p className="notice error">{message}</p>}<button className="primary" disabled={busy}>{busy?'Working…':mode==='login'?'Sign in':'Create LedgerX account'}</button></form><small>Portfolio environment · no real money is processed.</small></section></main>;
 const nav=(v:View)=>{setView(v);setMessage('');setNewSecret('')};
 return <main className="app-shell"><aside><div className="logo"><b>LX</b><span>LedgerX</span></div><nav><button className={view==='overview'?'selected':''} onClick={()=>nav('overview')}>Overview</button><button className={view==='webhooks'?'selected':''} onClick={()=>nav('webhooks')}>Webhooks</button><button className={view==='system'?'selected':''} onClick={()=>nav('system')}>System</button></nav><div className="profile"><div>{user.name[0].toUpperCase()}</div><span><b>{user.name}</b><small>{user.email}</small></span></div></aside><section className="content"><header><div><p className="eyebrow">{view.toUpperCase()}</p><h2>{view==='overview'?'Financial dashboard':view==='webhooks'?'Webhook operations':'System health'}</h2></div><button className="ghost" onClick={()=>{localStorage.removeItem('ledgerx_token');setToken('');setUser(null)}}>Sign out</button></header>{message&&<p className="notice">{message}</p>}
 {view==='overview'&&<><div className="stats"><article className="balance-card"><span>Available balance</span><strong>{balance}</strong><small>{wallet?.currency} · simulated funds</small><button onClick={fund} disabled={busy}>+ Add R$ 100</button></article><article><span>Ledger status</span><strong className="good">Balanced</strong><small>Double-entry invariant</small></article><article><span>Transfers</span><strong>{transfers.length}</strong><small>Posted transactions</small></article></div><div className="panels"><section className="panel"><p className="eyebrow">NEW TRANSFER</p><h3>Move simulated funds</h3><form className="transfer-form" onSubmit={transfer}><label>Destination wallet ID<input name="walletId" required/></label><label>Amount in cents<input name="amount" type="number" min="1" required/></label><button className="primary" disabled={busy}>Post transfer</button></form></section><section className="panel"><p className="eyebrow">YOUR WALLET</p><h3>Wallet identity</h3><div className="wallet-id">{wallet?.id}</div><p className="muted">Share this ID with another demo account.</p></section></div><section className="panel history"><div className="panel-title"><div><p className="eyebrow">LEDGER ACTIVITY</p><h3>Recent transfers</h3></div><span>{transfers.length} records</span></div>{transfers.length===0?<div className="empty">No transfers yet.</div>:<div className="table">{transfers.map(t=><div className="row" key={t.id}><div className="tx-icon">↗</div><div><b>{t.fromWalletId===wallet?.id?'Sent':'Received'}</b><small>{new Date(t.createdAt).toLocaleString('pt-BR')}</small></div><span className={t.fromWalletId===wallet?.id?'negative':'positive'}>{t.fromWalletId===wallet?.id?'-':'+'}{money(t.amountMinor,t.currency)}</span><em>{t.status}</em></div>)}</div>}</section></>}
 {view==='webhooks'&&<><div className="panels"><section className="panel"><p className="eyebrow">ENDPOINT</p><h3>Register signed webhook</h3><form className="transfer-form webhook-form" onSubmit={createWebhook}><label>HTTPS endpoint URL<input name="url" type="url" required placeholder="https://example.com/webhooks/ledgerx"/></label><button className="primary" disabled={busy}>Create endpoint</button></form>{newSecret&&<div className="secret"><b>Signing secret — shown once</b><code>{newSecret}</code><small>Store this securely. LedgerX will not display it again.</small></div>}</section><section className="panel"><p className="eyebrow">DELIVERY MODEL</p><h3>HMAC-SHA256</h3><p className="muted">Events are delivered asynchronously from the transactional outbox through BullMQ with exponential retries and a dead-letter queue.</p></section></div><section className="panel history"><div className="panel-title"><div><p className="eyebrow">REGISTERED</p><h3>Webhook endpoints</h3></div><span>{endpoints.length} endpoints</span></div>{endpoints.length===0?<div className="empty">No webhook endpoints registered.</div>:endpoints.map(e=><div className="endpoint" key={e.id}><span className={e.active?'dot on':'dot'}/><div><b>{e.url}</b><small>{new Date(e.createdAt).toLocaleString('pt-BR')}</small></div><em>{e.active?'ACTIVE':'DISABLED'}</em></div>)}</section><section className="panel history"><div className="panel-title"><div><p className="eyebrow">DELIVERIES</p><h3>Recent webhook attempts</h3></div><span>{deliveries.length} attempts</span></div>{deliveries.length===0?<div className="empty">Deliveries appear after a transfer produces an event.</div>:deliveries.map(d=><div className="endpoint" key={d.id}><span className={d.success?'dot on':'dot fail'}/><div><b>{d.event.type}</b><small>{d.endpoint.url} · attempt {d.attempt}</small></div><em>{d.statusCode}</em></div>)}</section></>}
 {view==='system'&&<><div className="stats system-stats"><article><span>API</span><strong className={health?.status==='ready'?'good':'warn'}>{health?.status??'Checking…'}</strong><small>Liveness + readiness</small></article><article><span>PostgreSQL</span><strong className={health?.checks?.postgres==='ok'?'good':'warn'}>{health?.checks?.postgres??'—'}</strong><small>Financial source of truth</small></article><article><span>Redis</span><strong className={health?.checks?.redis==='ok'||health?.checks?.redis==='disabled'?'good':'warn'}>{health?.checks?.redis??'—'}</strong><small>Queues and async delivery</small></article></div><section className="panel architecture"><p className="eyebrow">ARCHITECTURE</p><h3>Operational guarantees</h3><div className="guarantees"><div><b>Serializable</b><span>Concurrent financial writes</span></div><div><b>Idempotent</b><span>Safe request replay</span></div><div><b>Atomic outbox</b><span>Database + event consistency</span></div><div><b>Observable</b><span>Request IDs + Prometheus</span></div><div><b>Retryable</b><span>BullMQ exponential backoff</span></div><div><b>Recoverable</b><span>Dead-letter queue</span></div></div><button className="ghost refresh" onClick={loadSystem}>Refresh readiness</button></section></>}</section></main>
}
